### ISSUE TITLE
How to extract features

### ISSUE THREAD

**Issue by thoward27** [ctuning/ck#100] opened 2019-04-26 17:48 UTC
Thank you for all the work you have done putting this CK framework together!

## My Goal

I am now trying to use CK in my current pipeline, but cannot figure out how to extract program features (both static and dynamic). My goal is to be able to extract them on the fly in a python script.

Does anyone have any experience doing this? 

Ideally I'd like to be able to call a function like: `ck.compile(program, flags) -> features`

Any help would be greatly appreciated!

## My OS

```
$ ck detect platform.os

OS CK UOA:            linux-64 (4258b5fe54828a50)

OS name:              Ubuntu 19.04
Short OS name:        Linux 5.0.0
Long OS name:         Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
OS bits:              64
OS ABI:               x86_64

Platform init UOA:    42818da3a0789331
```

## Solution 1 (Failed)
Following the guidance found here: 
https://groups.google.com/forum/#!msg/collective-knowledge/klfCxdTnSqA/QCXe6oixBQAJ

Which recommends using:
```ck pipeline program:cbench-automotive-susan --speed --milepost --no_run --milepost_out_file=extracted-features.json```

I receive this error: 
```
 WARNING: no registered CK environment was found for required software  dependency with tags="compiler,lang-c,ctuning-cc" and setup={"host_os_uoa": "linux-64", "target_os_uoa": "linux-64", "target_os_bits": "64"}

  Trying to automatically detect required software ...
    No software auto-detection scripts found for this software in CK :( ...

       Checked following related CK soft entries:
        * compiler.ctuning-cc

  Searching and installing CK software packages ...
    * tags:        compiler,lang-c,ctuning-cc
    * or tags:     
    * no tags:     

    CK packages are not found for this software :( !
```

## Solution 2 (Failed)

Following guidance found here:
https://github.com/ctuning/ck/wiki/Reproducing-MILEPOST-project

Which recommends using:
```
ck pull all --kernel
ck pull repo:reproduce-milepost-project
apt-get install g++-multilib libc6-dev-i386
ck install package:compiler-ctuning-cc-2.5-plugins-src
```

At which point I select option 2, 
```
 2) compiler-gcc-4.4.4-milepost-src-deps  Version 4.4.4  (90da0e74d7477233)
```

After running the final line above, I receive this error:
```
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c:321: warning: dereferencing type-punned pointer will break strict-aliasing rules
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c:322: warning: dereferencing type-punned pointer will break strict-aliasing rules
/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj/./gcc/xgcc -B/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj/./gcc/ -B/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/x86_64-unknown-linux-gnu/bin/ -B/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/x86_64-unknown-linux-gnu/lib/ -isystem /home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/x86_64-unknown-linux-gnu/include -isystem /home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/x86_64-unknown-linux-gnu/sys-include -export-dynamic -ldl -g -fgnu89-inline -O2  -g -fgnu89-inline -DIN_GCC   -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wcast-qual -Wold-style-definition  -isystem ./include  -fPIC -g -DHAVE_GTHR_DEFAULT -DIN_LIBGCC2 -D__GCC_FLOAT_NOT_NEEDED   -I. -I. -I../.././gcc -I../../../milepost-gcc-4.4.4/libgcc -I../../../milepost-gcc-4.4.4/libgcc/. -I../../../milepost-gcc-4.4.4/libgcc/../gcc -I../../../milepost-gcc-4.4.4/libgcc/../include -I../../../milepost-gcc-4.4.4/libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT -DHAVE_CC_TLS -DUSE_TLS -o _mulvsi3_s.o -MT _mulvsi3_s.o -MD -MP -MF _mulvsi3_s.dep -DSHARED -DL_mulvsi3 -c ../../../milepost-gcc-4.4.4/libgcc/../gcc/libgcc2.c
make[3]: *** [../../../milepost-gcc-4.4.4/libgcc/shared-object.mk:12: unwind-dw2.o] Error 1
make[3]: *** Waiting for unfinished jobs....
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c: In function ‘add_fdes’:
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c:677: warning: dereferencing type-punned pointer will break strict-aliasing rules
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c: In function ‘linear_search_fdes’:
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c:795: warning: dereferencing type-punned pointer will break strict-aliasing rules
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c: In function ‘binary_search_unencoded_fdes’:
../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2-fde.c:843: warning: dereferencing type-punned pointer will break strict-aliasing rules
make[3]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj/x86_64-unknown-linux-gnu/libgcc'
make[2]: *** [Makefile:14272: all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj'
make[1]: *** [Makefile:17113: stage1-bubble] Error 2
make[1]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj'
make: *** [Makefile:741: all] Error 2
Error: Compilation failed in /home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj!

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           compiler-gcc-4.4.4-milepost-src-deps
   CK repo:              reproduce-milepost-project
   CK repo URL:          https://github.com/ctuning/reproduce-milepost-project
   CK package URL:       https://github.com/ctuning/reproduce-milepost-project/tree/master/package/compiler-gcc-4.4.4-milepost-src-deps
   Issues URL:           https://github.com/ctuning/reproduce-milepost-project/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Please, submit the log to the authors of this external CK package at "https://github.com/ctuning/reproduce-milepost-project/issues" to collaboratively fix this problem!

CK error: [package] package installation failed!
```

## Solution 3 (Failed)

Following guidance found here:
https://github.com/ctuning/reproduce-milepost-project

Which recommends:
```
sudo apt-get update && apt-get install -y python-all git bzip2 sudo wget zip
sudo pip install ck
sudo apt-get install -y libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev python-pillow
sudo apt-get install -y build-essential automake autoconf libncurses-dev uuid-runtime m4
sudo apt-get install -y gcc g++ g++-multilib libc6-dev-i386
sudo apt-get install -y texinfo libisl-dev libcloog-isl-dev libmpc-dev libgmp-dev libmpfr-dev
ck pull repo:reproduce-milepost-project
ck install package:compiler-gcc-4.4.4-milepost-src-deps
```

After running the final line above, I receive this error:
```
make[3]: *** [../../../milepost-gcc-4.4.4/libgcc/shared-object.mk:12: unwind-dw2.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj/x86_64-unknown-linux-gnu/libgcc'
make[2]: *** [Makefile:14272: all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj'
make[1]: *** [Makefile:17113: stage1-bubble] Error 2
make[1]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj'
make: *** [Makefile:741: all] Error 2
Error: Compilation failed in /home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj!

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           compiler-gcc-4.4.4-milepost-src-deps
   CK repo:              reproduce-milepost-project
   CK repo URL:          https://github.com/ctuning/reproduce-milepost-project
   CK package URL:       https://github.com/ctuning/reproduce-milepost-project/tree/master/package/compiler-gcc-4.4.4-milepost-src-deps
   Issues URL:           https://github.com/ctuning/reproduce-milepost-project/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Please, submit the log to the authors of this external CK package at "https://github.com/ctuning/reproduce-milepost-project/issues" to collaboratively fix this problem!

CK error: [package] package installation failed!
```

Additionally, this solution poses using `ck install package:compiler-gcc-4.4.4-milepost-src-no-deps`, which produces this error:
```
make[3]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj/x86_64-unknown-linux-gnu/libgcc'
make[2]: *** [Makefile:14272: all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj'
make[1]: *** [Makefile:17113: stage1-bubble] Error 2
make[1]: Leaving directory '/home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj'
make: *** [Makefile:741: all] Error 2
Error: Compilation failed in /home/tom/CK-TOOLS/gcc-milepost-4.4.4-linux-64/obj!

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           compiler-gcc-4.4.4-milepost-src-no-deps
   CK repo:              reproduce-milepost-project
   CK repo URL:          https://github.com/ctuning/reproduce-milepost-project
   CK package URL:       https://github.com/ctuning/reproduce-milepost-project/tree/master/package/compiler-gcc-4.4.4-milepost-src-no-deps
   Issues URL:           https://github.com/ctuning/reproduce-milepost-project/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Please, submit the log to the authors of this external CK package at "https://github.com/ctuning/reproduce-milepost-project/issues" to collaboratively fix this problem!

CK error: [package] package installation failed!
```

**Comment by gfursin** [comment] 2019-04-28 16:10
Hi @thoward27! Once again thanks a lot for your feedback - that helps us to improve related CK components.

I went through your 3 steps and did the following fixes:

1) I updated our CK program pipeline: https://github.com/ctuning/ck-autotuning/commit/9f1874beb27d7a6f76f9ee498b8c0999cec419bc . 

Now, when users want to extract milepost features and "reproduce-milepost-project" repo is not installed, I will detect that and will ask if they want to install this repo. If yes, CK will automatically install this repo and will continue extracting features ...

I also added reference to the CK repo "reproduce-milepost-project" in the software detection plugin for ctuning-cc (https://github.com/ctuning/ck-env/commit/03735275c63f08a9c72367ef5dc41b60a5c6aac2). It was done before I added "reproduce-milepost-project" ;) .

2) There is a typo. It should be "ck install package:compiler-ctuning-cc-2.5-plugins-src" instead of "ck install package:compiler-ctuning-cc-2.5-plugins-src-linux". I updated the wiki and it works now.

3) That is the most tricky part which is not related to CK because it's nowadays very difficult to build old MILEPOST GCC 4.x on newer systems. 

Most of the time you will not be able to use "compiler-gcc-4.4.4-milepost-src-no-deps" since it relies on your native packages such as GMP, ISL, MPFR, etc, which are most likely incompatible with 10-years old GCC. 

That's why you were right to use "compiler-gcc-4.4.4-milepost-src-no-deps". It attempts to build older sub-dependencies (Cloog, GMP, ISL, MPFR, texinfo) which are compatible with this old GCC. I just tried to build it from scratch via CK on my Ubuntu 16.04 with GCC 8.x:

```
fursin@velociti:~/CK/ck-env$ ck detect platform.os

OS CK UOA:            linux-64 (4258b5fe54828a50)

OS name:              Ubuntu 16.04.6 LTS
Short OS name:        Linux 4.4.0
Long OS name:         Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
OS bits:              64
OS ABI:               x86_64

Platform init UOA:    42818da3a0789331
```

and it worked. I even managed to extract static features!

May I ask you to tell me which OS are you using? 

Also you probably need to provide the full log because I expect that some sub-dependency failed. It's not related to CK but to building old deps in newer environment. If it's the case, I am not sure if I can help though sometimes using another GCC helps.

**Comment by gfursin** [comment] 2019-04-28 16:56
I just tried to install milepost gcc natively on Ubuntu 18.04:
```
fursin@fgg-t470p:~/CK/reproduce-milepost-project/package/compiler-gcc-4.4.4-milepost-src-deps/.cm$ ck detect platform.os

OS CK UOA:            linux-64 (4258b5fe54828a50)

OS name:              Ubuntu 18.04.2 LTS
Short OS name:        Linux 4.15.0
Long OS name:         Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
OS bits:              64
OS ABI:               x86_64

Platform init UOA:    42818da3a0789331
fursin@fgg-t470p:~/CK/reproduce-milepost-project/package/compiler-gcc-4.4.4-milepost-src-deps/.cm$ ck show env --tags=gcc
Env UID:         Target OS:      Bits: Name:                    Version: Tags:

2f085e1fcccd3c45        linux-64    64 GNU C compiler           8.2.0    64bits,compiler,gcc,host-os-linux-64,lang-c,lang-cpp,target-os-linux-64,v8,v8.2,v8.2.0
72e8c0b6b9794358        linux-64    64 GNU C compiler           7.3.0    64bits,compiler,gcc,host-os-linux-64,lang-c,lang-cpp,target-os-linux-64,v7,v7.3,v7.3.0
```

It fails here:
```
...
In file included from ../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2.c:333:
../../../milepost-gcc-4.4.4/libgcc/../gcc/config/i386/linux-unwind.h: In function ‘x86_64_fallback_frame_state’:
../../../milepost-gcc-4.4.4/libgcc/../gcc/config/i386/linux-unwind.h:54: error: dereferencing pointer to incomplete type
...
In file included from ../../../milepost-gcc-4.4.4/libgcc/../gcc/unwind-dw2.c:333:
../../../milepost-gcc-4.4.4/libgcc/../gcc/config/i386/linux-unwind.h: In function ‘x86_64_fallback_frame_state’:
../../../milepost-gcc-4.4.4/libgcc/../gcc/config/i386/linux-unwind.h:54: error: dereferencing pointer to incomplete type
../../../milepost-gcc-4.4.4/libgcc/shared-object.mk:15: recipe for target 'unwind-dw2_s.o' failed
...
```

I Googled this problem and it seems that there is something related to this error here: https://stackoverflow.com/questions/46999900/how-to-compile-gcc-6-4-0-with-gcc-7-2-in-archlinux .

@thoward27 - can you please investigate it further on your system, please. Unfortunately, the CK package "compiler-gcc-4.4.4-milepost-src-deps" is old so you can't automatically rebuild it. Instead, you can edit process.sh in this package entry to skip overwriting of source files and configuration to rebuild this package:
```
$ cd `ck find package:compiler-gcc-4.4.4-milepost-src-deps`
$ vim process.sh
```

If you find a solution to this problem, it will be possible to add a patch to this package which can be invoked only on a specific version of Ubuntu similar to this package: https://github.com/ctuning/ck-env/blob/master/package/compiler-llvm-8.0.0-universal/custom.py ...

**Comment by thoward27** [comment] 2019-04-29 13:31
Hello @gfursin! Thank you very much for your detailed response. 

I have updated my original comment to include my OS and expanded on the error from solution 2, which was generated following the new wiki recommendations. 

I still have not found a way to solve my problem, but if I do I will certainly add a patch for it!

**Comment by gfursin** [comment] 2019-04-30 11:10
Thanks @thoward27 . 

Oh, you use even newer Ubuntu (19.04). I know that it's getting harder and harder to compiler MILEPOST GCC natively. 

That's why I hope that the community will develop a new plugin for the latest GCC and LLVM to extract different features and without the need to recompile the whole compiler (that's why I helped to introduce plugins to GCC at first place but just didn't have time and resources to continue this project). 

I also suggest to follow the new MLIR project: https://github.com/tensorflow/mlir . I saw a blog post where they want to revive ML for compiler optimizations: https://medium.com/tensorflow/mlir-a-new-intermediate-representation-and-compiler-framework-beba999ed18d !

**Comment by thoward27** [comment] 2019-05-02 20:56
Thank you @gfursin, can you point me to your work on GCC plugins?

**Comment by gfursin** [comment] 2019-05-03 21:39
Here it is @thoward27:
* https://gcc.gnu.org/wiki/InteractiveCompilationInterface
* https://gcc.gnu.org/wiki/GCC_PluginComparison
* https://gcc.gnu.org/wiki/plugins-branch
* http://gcc.gnu.org/wiki/plugins
It may be very outdated though ;) I had a pleasure to collaborate with Google and Mozilla in 2010 to add the plugin framework to GCC which was relatively compatible with MILEPOST GCC interfaces at that time.  However, I am not sure about the current status - I didn't follow the project for some time now ...

**Comment by gfursin** [comment] 2019-05-29 14:33
I close this issue here because it relates to MILEPOST GCC and not CK framework itself.

**Closed by gfursin** 2019-05-29 14:33 UTC
Labels: enhancement
