### ISSUE TITLE
ck install package:lib-caffe-bvlc-master-cuda-universal FAILS ubuntu18.04

### ISSUE THREAD

**Issue by drandynisbet** [ctuning/ck#87] opened 2018-06-14 16:09 UTC
Seems to be an issue regarding linkage with -lpthreads rather than -lpthread?

Taken from .... /home/drandynisbet/CK/local/env/bdcc04179adab687/obj/CMakeFiles/CMakeError.log
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/drandynisbet/CK/local/env/bdcc04179adab687/obj/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_09f19/fast"
/usr/bin/make -f CMakeFiles/cmTC_09f19.dir/build.make CMakeFiles/cmTC_09f19.dir/build
make[1]: Entering directory '/home/drandynisbet/CK/local/env/bdcc04179adab687/obj/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_09f19.dir/CheckFunctionExists.c.o
/usr/bin/gcc-7   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_09f19.dir/CheckFunctionExists.c.o   -c /usr/share/cm
ake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_09f19
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_09f19.dir/link.txt --verbose=1
/usr/bin/gcc-7    -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_09f19.dir/CheckFunctionExists.c.o  -o cmTC_
09f19 -lpthreads 
/usr/bin/x86_64-linux-gnu-ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_09f19.dir/build.make:97: recipe for target 'cmTC_09f19' failed
make[1]: *** [cmTC_09f19] Error 1
make[1]: Leaving directory '/home/drandynisbet/CK/local/env/bdcc04179adab687/obj/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_09f19/fast' failed
make: *** [cmTC_09f19/fast] Error 2

**Comment by gfursin** [comment] 2018-06-14 18:59
Hi Andy,
I can't reproduce your error. I made a Docker image for Ubuntu 18.04 and installed Caffe via CK there. Maybe you selected some broken package during installation. Can you please attach the whole log including selections. Can you also attach another log from this command, please:
```
$ ck show env
```
Thanks a lot!

**Comment by drandynisbet** [comment] 2018-06-15 08:21
Howdy,
Im sure I will have done something stupid. Didnt detect my gcc
automatically - using  a python 2.7, this machine is an upgrade from a
previous ubuntu but not an LTS.

I/we plan to start using ck in order to make artefact evaluation easier ...
so Im starting to experiment with it ...

Cheers,
Andy

**Comment by gfursin** [comment] 2018-06-15 10:51
Sure - don't hesitate to ask if you have questions/issues. You can also consider joining CK Slack channel or post to CK mailing list: https://github.com/ctuning/ck/wiki/Contacts . Good luck ;) !

**Comment by gfursin** [comment] 2018-06-15 10:52
Also, when you have some issues, just attach the full log including CK commands - it's usually enough to identify and fix problems on our side ...

**Comment by psyhtest** [comment] 2018-07-18 20:42
Hi Andy, Just wondering you managed to make any progress?

**Comment by psyhtest** [comment] 2018-10-07 22:09
Closing as no feedback. Please feel free to reopen if still relevent.

**Closed by psyhtest** 2018-10-07 22:09 UTC
Labels: enhancement, question
