### ISSUE TITLE
Cannot find GCC for android OS 

### ISSUE THREAD

**Issue by sf-wind** [ctuning/ck#84] opened 2018-01-30 01:22 UTC
```
(ck2) feisun-mbp:CK feisun$ ck detect soft:compiler.gcc.android.ndk --target_os=android25-arm-v7a

  Searching for Android NDK GCC compiler (ndk-build) to automatically register in the CK - it may take some time, please wait ...

    * Searching in /usr ...
    * Searching in /opt ...
    * Searching in /Users/feisun ...

  Search completed in 67.8 secs. Found 0 target files (may be pruned) ...
****** Installation notes: ******
You can download and install Native Android NDK for your platform from
* http://developer.android.com/ndk/downloads/index.html

You can also download CrystaX NDK (extra libs and improved C++ support) from
* https://www.crystax.net/en/download


*********************************
CK error: [soft] software was not automatically found on your system! Please, install it and re-try again!!
```

However, there are multiple versions of the gcc under /opt and /Users/feisun/Library/Android/sdk/

```
feisun-mbp:ndk-bundle feisun$ find /opt/android_ndk/android-ndk-r15 -name "gcc" | grep android
/opt/android_ndk/android-ndk-r15/toolchains/x86-4.9/prebuilt/darwin-x86_64/libexec/gcc
/opt/android_ndk/android-ndk-r15/toolchains/x86-4.9/prebuilt/darwin-x86_64/lib/gcc
/opt/android_ndk/android-ndk-r15/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/libexec/gcc
/opt/android_ndk/android-ndk-r15/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc
/opt/android_ndk/android-ndk-r15/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/libexec/gcc
/opt/android_ndk/android-ndk-r15/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/lib/gcc
/opt/android_ndk/android-ndk-r15/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/libexec/gcc
/opt/android_ndk/android-ndk-r15/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc
/opt/android_ndk/android-ndk-r15/toolchains/mipsel-linux-android-4.9/prebuilt/darwin-x86_64/libexec/gcc
/opt/android_ndk/android-ndk-r15/toolchains/mipsel-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc
/opt/android_ndk/android-ndk-r15/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/libexec/gcc
/opt/android_ndk/android-ndk-r15/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc
```

I have a couple of other installed too. It is weird that none can be found. 

What is the likely cause? Thanks.

**Comment by gfursin** [comment] 2018-01-30 17:54
Thanks again  @sf-wind. I was providing support for Linux, Windows and Android, while MacOS is currently partially supported. But such feedback helps to improve related software detection plugin (https://github.com/ctuning/ck-env/blob/master/soft/compiler.gcc.android.ndk/customize.py). I added my colleagues to CC who uses MacOS - they will try to check it and fix a problem. We usually search for ndk-build on Linux to detect Android NDK and GCC, but maybe it's different on MacOS. I will also download MacOS distro and check the structure ... Will keep in touch ...

**Comment by sf-wind** [comment] 2018-01-30 18:31
Thanks for your response. I took a brief look of the code you referenced. It seems you only consider windows and linux in the code. So I'm wondering whether MacOS is supported or tested at all?

**Comment by gfursin** [comment] 2018-01-30 19:03
We do test some code on MacOS but unfortunately not thoroughly at the moment. 
Since we are limited in resources, we have to focus on those platforms which are of the most interest to our users. We also noticed that most of software plugins work fine on both Linux and MacOS (with a difference of dynamic libs which already specialized for MacOS in many cases). 
We now start having requests from MacOS users so we will be gradually improving plugins and experimental workflows for MacOS based on user feedback (that's the point of our open framework - to collaboratively improve all plugins to make them work on different platforms)...

**Comment by sf-wind** [comment] 2018-01-30 20:28
Thanks for your response! I hope MacOS can be fully supported soon.

**Comment by gfursin** [comment] 2018-01-30 22:12
I agree - we actually started improving plugins for MacOS a few weeks ago: https://github.com/ctuning/ck-env/pulls?q=is%3Apr+is%3Aclosed and I expect to continue that ... So, really sorry for inconvenience!

**Comment by ens-lg4** [comment] 2018-02-06 13:29
Dear @sf-wind, I'm currently trying to reproduce your case.

Can I ask why the android-ndk-r15 directory ended up in /opt/android_ndk on your machine?
Did you just choose to put it there yourself, or was it some kind of automatic installation?

**Comment by ens-lg4** [comment] 2018-02-20 17:37
Dear @sf-wind , I have made a patch that addresses your issue some time ago:
https://github.com/ctuning/ck-env/pull/63/commits/66e51465b21b59bd2cd61500692e11b1cc685fbf

Could you please pull the ck-env repository and have another go?
It would be very helpful to know whether it fixed your issue or not.

Many thanks in advance.

**Comment by gfursin** [comment] 2018-06-14 19:13
Since we didn't get a user feedback and it seems that we solved the problem, I close this ticket - we will reopen it if we encounter similar issue again... Thanks!

**Closed by gfursin** 2018-06-14 19:13 UTC
Labels: enhancement, help wanted, waiting for user input
