### ISSUE TITLE
Unicode error when installing CK using pip on Windows

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck#74] opened 2017-03-06 16:54 UTC
Hi, 

I tried to install CK on a fresh Windows 10 64 bit. I installed Git for Windows 2.12.0. Then I installed Python 3.6.0 for Windows from the official site. Then I opened `cmd.exe` and type `pip install ck`. I got the follwing message:

```
>pip install ck
Collecting ck
  Using cached ck-1.8.7.tar.gz
Installing collected packages: ck
  Running setup.py install for ck ... error
Exception:
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 83: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 83: invalid continuation byte
```

I'm not sure if it's pip's or CK's problem.

**Comment by gfursin** [comment] 2017-03-06 20:13
Very strange - can't reproduce it. I downloaded python 3.6-32 bit with pip, tried to install CK and it was fine:

C:\Python36-32\Scripts>pip.exe install ck
Collecting ck
  Using cached ck-1.8.7.tar.gz
Installing collected packages: ck
  Running setup.py install for ck ... done
Successfully installed ck-1.8.7

But it's Windows 10 64-bit machine with lots of installed stuff ... We plan to get a new Windows machine within a week and will try it there ...

**Comment by gfursin** [comment] 2017-03-06 20:22
Actually, can you please try to run python setup.py install instead?
Will it work? Or will produce similar error?

**Comment by dsavenko** [comment] 2017-03-07 03:25
OK, apparently this error was because I installed Python in C:\Program Files (for all users) instead of for my user only. This means pip should've been run with administrator privileges, which I didn't realize. Instead of normal warning, it gave me this gibberish about Unicode.

I re-installed python just for me (into my home folder), and was able to install CK.

However, I now have a warning from Python each time I run CK:

```
C:\Users\creat>ck status
C:\Users\creat\AppData\Local\Programs\Python\Python36-32\lib\runpy.py:125: RuntimeWarning: 'ck.kernel' found in sys.modules after import of package 'ck', but prior to execution of 'ck.kernel'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Your version is up-to-date: V1.8.7
```

Don't know what it's about, but aside from this warning, CK seems to work fine. Need to investigate a bit. I will do it in the evening from home, because this is reproducible on my home machine only.

**Comment by gfursin** [comment] 2017-03-07 08:46
Yes, very strange - I check it with Python 3.6-32 on my wife's machine and do not get these messages ...

**Comment by gfursin** [comment] 2018-06-14 19:14
Since we didn't get new comments with the same issue, I close it. We will reopen it if we get similar issue again. Thanks!

**Closed by gfursin** 2018-06-14 19:14 UTC
