### ISSUE TITLE
The 'ck cp' command doesn't change 'data_name' in meta.json

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck#70] opened 2017-01-12 08:51 UTC
Hi,

Say, I do this (repo and entry names are not important and given just as an example):

```
$ ck cp ck-caffe:program:caffe-classification ck-caffe:program:caffe-test
```

A new entry program/caffe-test appears after this. It's `info.json` is correctly modified so, that 'data_name' is 'caffe-test' (it was 'caffe-classification' before).

However, the same field ('data_name') in `meta.json` is not changed and equals 'caffe-classification'. 

Probably, it should be set to 'caffe-test' as well.

**Comment by gfursin** [comment] 2017-01-12 10:03
I actually also noticed this a few days when renaming entries, so I confirm this. The problem is that "data_name" can be used as a user-friendly name of this entry (which can be visualized in the web), so it may not be necessarily equal to alias. BUT I think I know the solution - I should check that if it is equal to the entry alias, then I should change it, otherwise not ... I will try to fix it at some point! Thanks again for noting!

**Comment by gfursin** [comment] 2017-01-13 09:38
I believe I fixed this problem and committed to 'ck-autotuning' repo ... The thing is that "cp" function is "overloaded" in ck-autotuning:module:program to update program meta when copying entries. I added update of backup_uid, but forgot to add update of "data_name" there. Thanks for noting ...

**Closed by gfursin** 2017-01-13 09:38 UTC
Labels: bug
